name: Revision BootCamp2020 Class-2

on: 
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v-2
    
    - name: Installing Node JS environment 
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Github Actions for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with: 
        cmd: install
    - name: Installing surge
      run: npm install -g surge
      
    - name: deploying on surge
    
      run: surge ./build Rev-bootcapm2020_class2.surge.sh --token $ {{ secrets.SURGE_TOKEN }}
      
      
    
